
package home;

import java.awt.*;
import javax.swing.*;

public class DisplayHome extends javax.swing.JPanel {
    private String UserName;        // User's profile name
    private int IntMovies;          // Number of movies on watchlist (interested)
    private int WatchedMovies;      // Number of movies watched
    private int IntShows;           // Number of shows on watchlist (interested)
    private int WatchedShows;       // Number of shows watched
    
    /**
     * Creates new form DisplayHome
     */
    public DisplayHome() {
        initComponents();
    }
    
    /**
     * Overloaded Constructor
     * 
     * @param UserName for profile
     * @param movieReader to read movie data file
     * @param showReader to read show data file
     */
    public DisplayHome(String UserName, MovieJSONEditor movieReader, TVJSONEditor showReader) {
        initComponents();
        this.UserName = UserName;
        this.IntMovies = movieReader.getNumInterestedMovies();
        this.WatchedMovies = movieReader.getNumWatchedMovies();
        this.IntShows = showReader.getNumInterestedShows();
        this.WatchedShows = showReader.getNumWatchedShows();
        
        displayComponents();
    }
    
    
    /**
     * Setup UI for JPanel
     */
    private void displayComponents() {
        
        // Initialize fields with appropriate data
        displayName.setText("Welcome, " + UserName);
        movieInterestedLabel.setText("Movies in Watchlist: " + IntMovies);
        movieWatchedLabel.setText("Watched Movies: " + WatchedMovies);
        showInterestedLabel.setText("Shows in Watchlist: " + IntShows);
        showWatchedLabel.setText("Watched Shows: " + WatchedShows);
        
        // Initialize progress bars
        movieProgress.setValue(calculatePercentage(WatchedMovies, IntMovies));
        movieProgress.setStringPainted(true);
        showProgress.setValue(calculatePercentage(WatchedShows, IntShows));
        showProgress.setStringPainted(true);
    }
    
    /**
     * Calculate progress percentage for movies and shows
     * 
     * @param part number of items watched
     * @param total number of items in watch list
     * @return Percentage of watch progress
     */
    private int calculatePercentage(int part, int total) {
        if(total != 0)
            return ( (part * 100) / total );
        else
            return 0;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayName = new javax.swing.JLabel();
        dashboardDisplay = new javax.swing.JPanel();
        movieStatsContainer = new javax.swing.JPanel();
        movieSectionTitle = new javax.swing.JLabel();
        movieInterestedLabel = new javax.swing.JLabel();
        movieWatchedLabel = new javax.swing.JLabel();
        movieProgress = new javax.swing.JProgressBar();
        showStatsContainer = new javax.swing.JPanel();
        showSectionTitle = new javax.swing.JLabel();
        showInterestedLabel = new javax.swing.JLabel();
        showWatchedLabel = new javax.swing.JLabel();
        showProgress = new javax.swing.JProgressBar();

        displayName.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        displayName.setText("UserName");

        dashboardDisplay.setLayout(new java.awt.BorderLayout());

        movieSectionTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        movieSectionTitle.setText("Movies");

        movieInterestedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        movieInterestedLabel.setText("Interested Movies");

        movieWatchedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        movieWatchedLabel.setText("Watched Movies");

        javax.swing.GroupLayout movieStatsContainerLayout = new javax.swing.GroupLayout(movieStatsContainer);
        movieStatsContainer.setLayout(movieStatsContainerLayout);
        movieStatsContainerLayout.setHorizontalGroup(
            movieStatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movieStatsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movieStatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movieInterestedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movieSectionTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movieWatchedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movieProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE))
                .addContainerGap())
        );
        movieStatsContainerLayout.setVerticalGroup(
            movieStatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movieStatsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieSectionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movieInterestedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movieWatchedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(movieProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        dashboardDisplay.add(movieStatsContainer, java.awt.BorderLayout.CENTER);

        showSectionTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        showSectionTitle.setText("TV Shows");

        showInterestedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        showInterestedLabel.setText("Interested Shows");

        showWatchedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        showWatchedLabel.setText("Watched Shows");

        javax.swing.GroupLayout showStatsContainerLayout = new javax.swing.GroupLayout(showStatsContainer);
        showStatsContainer.setLayout(showStatsContainerLayout);
        showStatsContainerLayout.setHorizontalGroup(
            showStatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showStatsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showStatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showSectionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showInterestedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showWatchedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE))
                .addContainerGap())
        );
        showStatsContainerLayout.setVerticalGroup(
            showStatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showStatsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showSectionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showInterestedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showWatchedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dashboardDisplay.add(showStatsContainer, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardDisplay;
    private javax.swing.JLabel displayName;
    private javax.swing.JLabel movieInterestedLabel;
    private javax.swing.JProgressBar movieProgress;
    private javax.swing.JLabel movieSectionTitle;
    private javax.swing.JPanel movieStatsContainer;
    private javax.swing.JLabel movieWatchedLabel;
    private javax.swing.JLabel showInterestedLabel;
    private javax.swing.JProgressBar showProgress;
    private javax.swing.JLabel showSectionTitle;
    private javax.swing.JPanel showStatsContainer;
    private javax.swing.JLabel showWatchedLabel;
    // End of variables declaration//GEN-END:variables
}
