package home;

import java.util.*;
import java.awt.*;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author salwajeries
 */
public class DisplayMovies extends javax.swing.JPanel {

    private ArrayList<Movie> Movies;
    private DefaultListModel movieModel;
    private final String posterFetchURL = "https://image.tmdb.org/t/p/w300_and_h450_bestv2";
    private MovieJSONEditor movieReader;
    
    /**
     * Default Constructor
     */
    public DisplayMovies() {
        initComponents();
    }
    
    /**
     * Overloaded Constructor
     * 
     * @param movieReader
     */
    //public DisplayMovies(ArrayList<Movie> importMovies, MovieJSONEditor movieReader) {
    public DisplayMovies(MovieJSONEditor movieReader) {
        initComponents();
        this.movieReader = new MovieJSONEditor();
        this.movieReader = movieReader;
        //this.Movies = importMovies;
        this.Movies = movieReader.getAllMovies();
        
        // Create movie list model
        movieModel = new DefaultListModel<String>();
        for(Movie m : Movies) {
            movieModel.addElement(m.getTitle());
        }
        movieList.setModel(movieModel);
        movieList.setSelectedIndex(0);      // Automatically select first item in list
    }
    
    
    /**
     * Display all movie information in the respective JLabels
     * 
     * @param currentMovie 
     */
    private void displayMovieInfo(Movie currentMovie) {
        
        // Initialize fields with movie data
        movieInterested.setSelected(currentMovie.getInterested());
        movieWatched.setSelected(currentMovie.getViewed());
        movieTagline.setText(currentMovie.getTagline());
        movieDesc.setText(currentMovie.getDescription());
        movieDesc.setEditable(false);
        movieDesc.setLineWrap(true);
        movieDesc.setWrapStyleWord(true);
        movieGenre.setText(currentMovie.getGenre());
        movieRDate.setText(currentMovie.getRDateString());
        movieRunT.setText(currentMovie.getRunTString());
        movieTitle.setText(currentMovie.getTitle());
        
        // Setup movie poster
        try {
            String movieURL = posterFetchURL + currentMovie.getArt();
            URL imageURL = new URL(movieURL);
            InputStream in = imageURL.openStream();
            Image image = ImageIO.read(in);
            
            int height = (int) movieArt.getSize().getHeight();
            int width = (int) movieArt.getSize().getHeight();
            image = image.getScaledInstance(200, 300, Image.SCALE_DEFAULT);
            
            movieArt.setIcon(new ImageIcon(image));
        }
        catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieListContainer = new javax.swing.JPanel();
        movieListScroll = new javax.swing.JScrollPane();
        movieList = new javax.swing.JList<>();
        displayMovieInfoContainer = new javax.swing.JPanel();
        displayMovieStatus = new javax.swing.JPanel();
        movieArt = new javax.swing.JLabel();
        movieInterested = new javax.swing.JCheckBox();
        movieWatched = new javax.swing.JCheckBox();
        displayMovieInfo = new javax.swing.JPanel();
        movieTitle = new javax.swing.JLabel();
        movieRDate = new javax.swing.JLabel();
        movieRunT = new javax.swing.JLabel();
        movieGenre = new javax.swing.JLabel();
        movieTagline = new javax.swing.JLabel();
        movieDescScroll = new javax.swing.JScrollPane();
        movieDesc = new javax.swing.JTextArea();

        movieList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        movieList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                movieListValueChanged(evt);
            }
        });
        movieListScroll.setViewportView(movieList);

        javax.swing.GroupLayout movieListContainerLayout = new javax.swing.GroupLayout(movieListContainer);
        movieListContainer.setLayout(movieListContainerLayout);
        movieListContainerLayout.setHorizontalGroup(
            movieListContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movieListContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        movieListContainerLayout.setVerticalGroup(
            movieListContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movieListContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieListScroll)
                .addContainerGap())
        );

        movieInterested.setText("Interested in this movie?");
        movieInterested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieInterestedActionPerformed(evt);
            }
        });

        movieWatched.setText("Watched this movie?");
        movieWatched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieWatchedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayMovieStatusLayout = new javax.swing.GroupLayout(displayMovieStatus);
        displayMovieStatus.setLayout(displayMovieStatusLayout);
        displayMovieStatusLayout.setHorizontalGroup(
            displayMovieStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMovieStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayMovieStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayMovieStatusLayout.createSequentialGroup()
                        .addComponent(movieArt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(movieInterested, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movieWatched, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        displayMovieStatusLayout.setVerticalGroup(
            displayMovieStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMovieStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieArt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(movieInterested)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movieWatched)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        movieTitle.setText("Title");

        movieRDate.setText("Release Date");

        movieRunT.setText("RunTime");

        movieGenre.setText("Genre");

        movieTagline.setText("Tagline");

        movieDesc.setColumns(20);
        movieDesc.setRows(5);
        movieDescScroll.setViewportView(movieDesc);

        javax.swing.GroupLayout displayMovieInfoLayout = new javax.swing.GroupLayout(displayMovieInfo);
        displayMovieInfo.setLayout(displayMovieInfoLayout);
        displayMovieInfoLayout.setHorizontalGroup(
            displayMovieInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMovieInfoLayout.createSequentialGroup()
                .addGroup(displayMovieInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayMovieInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(displayMovieInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movieTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(movieRDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(displayMovieInfoLayout.createSequentialGroup()
                                .addComponent(movieRunT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(movieGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(movieTagline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(movieDescScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
                .addContainerGap())
        );
        displayMovieInfoLayout.setVerticalGroup(
            displayMovieInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMovieInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movieRDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayMovieInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieRunT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(movieTagline, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(movieDescScroll)
                .addContainerGap())
        );

        javax.swing.GroupLayout displayMovieInfoContainerLayout = new javax.swing.GroupLayout(displayMovieInfoContainer);
        displayMovieInfoContainer.setLayout(displayMovieInfoContainerLayout);
        displayMovieInfoContainerLayout.setHorizontalGroup(
            displayMovieInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayMovieInfoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayMovieStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayMovieInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        displayMovieInfoContainerLayout.setVerticalGroup(
            displayMovieInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayMovieInfoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayMovieInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayMovieInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayMovieStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayMovieInfoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayMovieInfoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movieListContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Update display of movie information based on selected movie in list
     * 
     * @param evt 
     */
    private void movieListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_movieListValueChanged
        Movie currentMovie = new Movie();
        currentMovie = Movies.get(movieList.getSelectedIndex());
        displayMovieInfo(currentMovie);
    }//GEN-LAST:event_movieListValueChanged

    /**
     * Update movie interest status for current movie
     * 
     * @param evt 
     */
    private void movieInterestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieInterestedActionPerformed
        // Get movie object
        Movie currentMovie = Movies.get(movieList.getSelectedIndex());
        
        // Set movie interest status
        if(movieInterested.isSelected())
            currentMovie.setInterested(true);
        else
            currentMovie.setInterested(false);
        
        // Update movie object in JSON file
        try {
            movieReader.updateMovie(currentMovie);
        }
        catch (Exception e) {
            System.out.println("Uncaught Exeption - Did not update object");
        }
        
        // Re-display movie info
        displayMovieInfo(currentMovie);
    }//GEN-LAST:event_movieInterestedActionPerformed

    /**
     * Update movie watched status for current movie
     * 
     * @param evt 
     */
    private void movieWatchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieWatchedActionPerformed
        // Get movie object
        Movie currentMovie = Movies.get(movieList.getSelectedIndex());
        
        // Set movie watched status
        if(movieWatched.isSelected())
            currentMovie.setViewed(true);
        else
            currentMovie.setViewed(false);
        
        // Update movie object in JSON file
        try {
            movieReader.updateMovie(currentMovie);
        }
        catch (Exception e) {
            System.out.println("Uncaught Exeption - Did not update object");
        }
        
        // Re-display movie info
        displayMovieInfo(currentMovie);
    }//GEN-LAST:event_movieWatchedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayMovieInfo;
    private javax.swing.JPanel displayMovieInfoContainer;
    private javax.swing.JPanel displayMovieStatus;
    private javax.swing.JLabel movieArt;
    private javax.swing.JTextArea movieDesc;
    private javax.swing.JScrollPane movieDescScroll;
    private javax.swing.JLabel movieGenre;
    private javax.swing.JCheckBox movieInterested;
    private javax.swing.JList<String> movieList;
    private javax.swing.JPanel movieListContainer;
    private javax.swing.JScrollPane movieListScroll;
    private javax.swing.JLabel movieRDate;
    private javax.swing.JLabel movieRunT;
    private javax.swing.JLabel movieTagline;
    private javax.swing.JLabel movieTitle;
    private javax.swing.JCheckBox movieWatched;
    // End of variables declaration//GEN-END:variables
}
