package home;

import java.util.ArrayList;

abstract class Media {
    private final String Title;             // Title of media
    private final ArrayList<String> Genre;  // Genres of media
    private final String Description;       // Description of media
    private final String Tagline;           // One-liner that describes media
    private final String Art;               // Poster/Artwork URL for the media
    private final int ID;                   // Unique ID related to media object, generated by TheMovieDB API
    private boolean Interested;             // True/False Interest in media
    protected boolean Viewed;               // True/False Viewed status of media

    
    
    /**
     * Default Constructor
     */
    public Media(){
        this.Title = null;
        this.Genre = new ArrayList();
        this.Description = null;
        this.Tagline = null;
        this.Art = null;
        this.ID = 0;
        this.Interested = false;
        this.Viewed = false;
    }

    /**
     * Overloaded Media Constructor
     * 
     * @param Title of media
     * @param Genre list of media
     * @param Description of media
     * @param Tagline one-liner for media
     * @param Art for media
     * @param Interested status
     * @param Viewed status
     * @param ID unique to media
     */
    public Media(String Title, ArrayList<String> Genre, String Description, String Tagline, String Art, boolean Interested, boolean Viewed, int ID){
        
        this.Title = Title;
        
        this.Genre = new ArrayList();
        for(String g : Genre) {
            this.Genre.add(g);
        }
        
        this.Description = Description;
        this.Tagline = Tagline;
        this.Art = Art;
        this.ID = ID;
        this.Interested = Interested;
        this.Viewed = Viewed;
    }
    
    
    /**
     * Get Title
     * @return Title
     */
    public String getTitle(){
        return Title;
    }
    
    /**
     * Get Genre
     * @return Genre as formatted string
     */
    public String getGenre(){
        
        String GenreList = "";
        
        for(String g : Genre) {
            GenreList += g + ", ";
        }
        
        GenreList = GenreList.substring(0, GenreList.length()-2);       // Remove last comma character from loop
        return GenreList;
    }
    
    /**
     * Get Genre
     * @return Genre as ArrayList of Strings
     */
    public ArrayList<String> getGenreArray() {
        return Genre;
    }
    
    /**
     * Get Description
     * @return Description
     */
    public String getDescription(){
        return Description;
    }
    
    /**
     * Get Tagline
     * @return Tagline
     */
    public String getTagline(){
        return Tagline;
    }
    
    /**
     * Get Art
     * @return Art URL
     */
    public String getArt(){
        return Art;
    }
    
    /**
     * Get Object's Unique ID
     * @return ID
     */
    public int getID(){
        return ID;
    }
    
    /**
     * Get Interest Status
     * @return Interested
     */
    public boolean getInterested(){
        updateInterested();
        return Interested;
    }

    /**
     * Set Interest Status
     * Then Check for update in interest status 
     * @param Interested status
     */
    public void setInterested(boolean Interested){
        this.Interested = Interested;
        updateInterested();
    }
    
    /**
     * Update Interest Status for Override Case:
     * If viewed, interested must be true
     */
    public void updateInterested() {
        if(Viewed)
            this.Interested = true;
    }
    
    /**
     * Get Viewed Status
     * @return Viewed status
     */
    public abstract boolean getViewed();
    
    /**
     * Set Viewed Status
     * @param Viewed status
     */
    public abstract void setViewed(boolean Viewed);
    
}
