package home;

public class Season{
    private final String SeasonTitle;       // Title of season
    private final String SeasonDesc;        // Description of season
    private final String RDate;             // Release date of season
    private final int EpTotal;              // Number of episodes total in the season
    private int EpWatched;                  // Number of episodes watched in the season
    private final int SeasonID;             // Season Unique ID generated by TheMovieDB API
    private boolean SeasonWatched;          // Season watched status
    
    
    /**
     * Default Constructor
     */
    public Season(){
        // Initialize default instance variables
        this.SeasonTitle = null;
        this.SeasonDesc = null;
        this.RDate = null;
        this.EpTotal = 0;
        this.EpWatched = 0;
        this.SeasonID = 0;
        this.SeasonWatched = false;
    }
    
    /**
     * Overloaded Constructor
     * 
     * @param SeasonTitle
     * @param SeasonDesc
     * @param RDate
     * @param EpTotal
     * @param EpWatched
     * @param ID 
     */
    public Season(String SeasonTitle, String SeasonDesc, String RDate, int EpTotal, int EpWatched, int ID){
        this.SeasonTitle = SeasonTitle;
        this.SeasonDesc = SeasonDesc;
        this.EpTotal = EpTotal;
        this.EpWatched = EpWatched;
        this.SeasonID = ID;
        this.SeasonWatched = false;
        
        if(RDate == null)
            this.RDate = "";
        else
            this.RDate = RDate;
        
        // Check for update in season watched status
        updateSeasonWatched();
    }
    
    
    /**
     * Get Season Title
     * @return Title
     */
    public String getSeasonTitle(){
        return SeasonTitle;
    }
    
    /**
     * Get Season Description
     * @return Description
     */
    public String getSeasonDesc(){
        return SeasonDesc;
    }
    
    /**
     * Get Season Release Date
     * @return RDate
     */
    public String getRDate(){
        return RDate;
    }
    
    /**
     * Get Season Release Date as Formatted String
     * @return Formatted Release Date
     */
    public String getRDateString(){
        if(RDate == "")     // Check if RDate is null
            return "";
        
        String year = RDate.substring(0, 4);
        String month = RDate.substring(5, 7);
        String day = RDate.substring(8);
        return month + "/" + day + "/" + year;
    }
    
    /**
     * Get Number of Episodes in Season Total
     * @return EpTotal
     */
    public int getEpTotal(){
        return EpTotal;
    }
    
    /**
     * Get Number of Episodes in Season Watched
     * @return EpWatched
     */
    public int getEpWatched(){
        return EpWatched;
    }
    
    /**
     * Update Number of Episodes in Season Watched
     * Then, check for update in season watched status
     * GIVEN: epWatchedValue is a valid input, aka (0 - epWatchedValue - Total Episodes)
     * @param epWatchedValue new EpWatched value
     */
    public void setEpWatched(int epWatchedValue){
        EpWatched = epWatchedValue;
        updateSeasonWatched();     // Update Season Watched Status
    }
    
    /**
     * Get Season's Unique ID
     * @return SeasonID
     */
    public int getSeasonID(){
        return SeasonID;
    }
    
    /**
     * Get Season Watched Status
     * Then, check for update in season watched status
     * @return SeasonWatched
     */
    public boolean getSeasonWatched(){
        updateSeasonWatched();
        return SeasonWatched;
    }
    
    /**
     * Update Season Watched Status based on EpWatched Count
     */
    public void updateSeasonWatched(){
        if(EpWatched == EpTotal)
            SeasonWatched = true;
        else
            SeasonWatched = false;
    }
    
    /**
     * Explicitly Set Season Watched Status
     * @param WatchedStatus 
     */
    public void setSeasonWatched(boolean WatchedStatus){
        SeasonWatched = WatchedStatus;
        
        if(SeasonWatched)
            EpWatched = EpTotal;    // Set to all Ep Watched
        else
            EpWatched = 0;          // Reset EpWatched
    }
    
}
