/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import javax.swing.JLabel;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import java.io.File;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;

import java.io.IOException;
import java.io.UncheckedIOException;



/**
 *
 * @author salwajeries
 */
public class testHome extends javax.swing.JFrame {

    ArrayList<Movie> movies;
    ArrayList<TV_Show> shows;
    ArrayList<Webcomic> comics;
    
    DefaultListModel model;
    ListSelectionModel listSelectionModel;
    
    /**
     * Creates new form testHome
     */
    public testHome() {
        initComponents();
        customize();
    }
    
    public testHome(ArrayList<Movie> movieList) {
        initComponents();
        movies = movieList;
        customize();
        
        
    }
    
    private void customize() {
        model = new DefaultListModel<String>();
        
        for(Movie idx : movies) {
            model.addElement(idx.getTitle());
            System.out.println(idx.getTitle());
        }        
        
        moviesList.setModel(model);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navTabGroup = new javax.swing.JTabbedPane();
        moviesTab = new javax.swing.JPanel();
        moviesScroll = new javax.swing.JScrollPane();
        moviesList = new javax.swing.JList<>();
        displayInfoPage = new javax.swing.JPanel();
        movieTitle = new javax.swing.JLabel();
        movieArtSource = new javax.swing.JLabel();
        movieInterested = new javax.swing.JCheckBox();
        movieWatched = new javax.swing.JCheckBox();
        movieRDate = new javax.swing.JLabel();
        movieRating = new javax.swing.JLabel();
        movieRunT = new javax.swing.JLabel();
        movieGenre = new javax.swing.JLabel();
        movieCast = new javax.swing.JLabel();
        movieDescScroll = new javax.swing.JScrollPane();
        movieDesc = new javax.swing.JTextArea();
        tvTab = new javax.swing.JPanel();
        comicsTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moviesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        moviesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                moviesListValueChanged(evt);
            }
        });
        moviesScroll.setViewportView(moviesList);

        movieTitle.setText("Title");

        movieArtSource.setText("jLabel2");

        movieInterested.setText("Interested?");

        movieWatched.setText("Watched?");

        movieRDate.setText("jLabel1");

        movieRating.setText("jLabel1");

        movieRunT.setText("jLabel1");

        movieGenre.setText("jLabel1");

        movieCast.setText("jLabel1");

        movieDesc.setColumns(20);
        movieDesc.setRows(5);
        movieDescScroll.setViewportView(movieDesc);

        javax.swing.GroupLayout displayInfoPageLayout = new javax.swing.GroupLayout(displayInfoPage);
        displayInfoPage.setLayout(displayInfoPageLayout);
        displayInfoPageLayout.setHorizontalGroup(
            displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayInfoPageLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayInfoPageLayout.createSequentialGroup()
                        .addComponent(movieArtSource, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addGroup(displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movieTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(displayInfoPageLayout.createSequentialGroup()
                                .addGroup(displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(displayInfoPageLayout.createSequentialGroup()
                                        .addComponent(movieRDate)
                                        .addGap(18, 18, 18)
                                        .addComponent(movieRating))
                                    .addGroup(displayInfoPageLayout.createSequentialGroup()
                                        .addComponent(movieRunT)
                                        .addGap(18, 18, 18)
                                        .addComponent(movieGenre)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayInfoPageLayout.createSequentialGroup()
                                .addGroup(displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(movieDescScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                                    .addComponent(movieCast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(displayInfoPageLayout.createSequentialGroup()
                        .addGroup(displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movieInterested)
                            .addComponent(movieWatched))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        displayInfoPageLayout.setVerticalGroup(
            displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayInfoPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayInfoPageLayout.createSequentialGroup()
                        .addComponent(movieTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieRDate)
                            .addComponent(movieRating))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(displayInfoPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieRunT)
                            .addComponent(movieGenre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieDescScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieCast, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(movieArtSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movieInterested)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movieWatched)
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout moviesTabLayout = new javax.swing.GroupLayout(moviesTab);
        moviesTab.setLayout(moviesTabLayout);
        moviesTabLayout.setHorizontalGroup(
            moviesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moviesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayInfoPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        moviesTabLayout.setVerticalGroup(
            moviesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moviesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moviesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayInfoPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moviesScroll))
                .addContainerGap())
        );

        navTabGroup.addTab("Movies", moviesTab);

        javax.swing.GroupLayout tvTabLayout = new javax.swing.GroupLayout(tvTab);
        tvTab.setLayout(tvTabLayout);
        tvTabLayout.setHorizontalGroup(
            tvTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        tvTabLayout.setVerticalGroup(
            tvTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        navTabGroup.addTab("TV Shows", tvTab);

        javax.swing.GroupLayout comicsTabLayout = new javax.swing.GroupLayout(comicsTab);
        comicsTab.setLayout(comicsTabLayout);
        comicsTabLayout.setHorizontalGroup(
            comicsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        comicsTabLayout.setVerticalGroup(
            comicsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        navTabGroup.addTab("Comics", comicsTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navTabGroup)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navTabGroup)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moviesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_moviesListValueChanged
        // TODO add your handling code here:
        //System.out.println(moviesList.getSelectedValue());
        //movieTitle.setText(moviesList.getSelectedValue());
        displayMovieInfo(moviesList.getSelectedIndex());
    }//GEN-LAST:event_moviesListValueChanged

    
    private void displayMovieInfo(int movieIndex) {
        
        Movie movie1 = movies.get(movieIndex);
        //System.out.println(movie1.getTitle());
/*        
private javax.swing.JPanel movieArt;
    private javax.swing.JLabel movieCast;
    private javax.swing.JLabel movieDesc;
    private javax.swing.JLabel movieGenre;
    private javax.swing.JCheckBox movieInterested;
    private javax.swing.JLabel movieRDate;
    private javax.swing.JLabel movieRating;
    private javax.swing.JLabel movieRunT;
    private javax.swing.JLabel movieTitle;
    private javax.swing.JCheckBox movieWatched;
   */

    movieCast.setText(movie1.getCast());
    movieDesc.setText(movie1.getDescription());
    
    movieDesc.setEditable(false);
    movieDesc.setLineWrap(true);
    movieDesc.setWrapStyleWord(true);
    
    movieGenre.setText(movie1.getGenre());
    movieRDate.setText(movie1.getRDate());
    movieRating.setText(movie1.getRating());
    movieRunT.setText(Integer.toString(movie1.getRunT()));
    movieTitle.setText(movie1.getTitle());
    
    movieArtSource.setIcon(new ImageIcon("godfather_art.jpeg"));
    

    /*
        File getSource = movie1.getArt();
        
        try {
            BufferedImage img = ImageIO.read(getSource);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        JLabel picLabel = new JLabel(new ImageIcon(img));
        movieArt.add(picLabel);
        */
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel comicsTab;
    private javax.swing.JPanel displayInfoPage;
    private javax.swing.JLabel movieArtSource;
    private javax.swing.JLabel movieCast;
    private javax.swing.JTextArea movieDesc;
    private javax.swing.JScrollPane movieDescScroll;
    private javax.swing.JLabel movieGenre;
    private javax.swing.JCheckBox movieInterested;
    private javax.swing.JLabel movieRDate;
    private javax.swing.JLabel movieRating;
    private javax.swing.JLabel movieRunT;
    private javax.swing.JLabel movieTitle;
    private javax.swing.JCheckBox movieWatched;
    private javax.swing.JList<String> moviesList;
    private javax.swing.JScrollPane moviesScroll;
    private javax.swing.JPanel moviesTab;
    private javax.swing.JTabbedPane navTabGroup;
    private javax.swing.JPanel tvTab;
    // End of variables declaration//GEN-END:variables
}
